### PR TITLE
Fix for #302

### LINKED ISSUE #302: Add `Set Page size` option in text to PDF
We have `Set Page size` option in images to PDF. 
screen shot 2018-07-28 at 10 10 46 pm

### Expected behaviour
- Add same option in `Text to PDF` screen
- Don't just copy paste the code from ImagesToPDFrgament. Create a new utlity file (or add a new function in existing utils file) & use that code at both the place (imagestopdf & texttopdf)

### PR DESCRIPTION
**Pull request by vyankatesh24**
# Description
Added Set Page Size option in `TextToPdf`Fragment.

image

image

Fixes #302 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java [hunk 1]
```diff
@@ -100,9 +105,30 @@ public void onItemClick(int position) {
...
+                .positiveText(android.R.string.ok)
+                .negativeText(android.R.string.cancel)
+                .onPositive((dialog1, which) -> {
+                    View view = dialog1.getCustomView();
+                    RadioGroup radioGroup = view.findViewById(R.id.radio_group_page_size);
+                    int selectedId = radioGroup.getCheckedRadioButtonId();
+                    Spinner spinnerA = view.findViewById(R.id.spinner_page_size_a0_a10);
+                    Spinner spinnerB = view.findViewById(R.id.spinner_page_size_b0_b10);
+                    FileUtils utils = new FileUtils(mActivity);
+                    mPageSize = utils.getPageSize(selectedId, spinnerA.getSelectedItem().toString(),
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: Use `mFileUtils` here. No need to create new fileutils variable

File: app/src/main/java/swati4star/createpdf/util/FileUtils.java [hunk 2]
```diff
@@ -486,4 +489,46 @@ else if (scheme.equals("content")) {
         }
         return fileName;
     }
+
+    /**
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/FileUtils.java]: This file already has a lot of utils functions. Move this function to a new file `PageSizeUtils.java`
