### PR TITLE
Fixed issue #321

### LINKED ISSUE #321: Back button on any navigation bar activity closes the app
The back button on any side navigation bar closes the activity and user has to open the app again to access again

### PR DESCRIPTION
**Pull request by vishalkalra9**
# Description
Changes for opening default fragment on pressing back while on any other fragment. Also added a Toast for double back press on Default fragment. 

Fixes #321 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/activity/MainActivity.java [hunk 1]
```diff
@@ -170,8 +175,38 @@ public void onBackPressed() {
...
+    }
+
+    private void checkDoubleBackPress() {
+        if (mDoubleBackToExitPressedOnce) {
             super.onBackPressed();
+            return;
         }
+
+        this.mDoubleBackToExitPressedOnce = true;
+        Toast.makeText(this, "Press back again to exit", Toast.LENGTH_SHORT).show();
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/activity/MainActivity.java]: Add constant string to strings.xml file & use that here

**Comment by Swati4star** [comment]
Which commit are you talking about?
Your previous PR was successfully merged.

**Comment by vishalkalra9** [comment]
@Swati4star  I have made those changes
