### PR TITLE
fix:#131 catch files shared by other apps

### LINKED ISSUE #131: Catch files shared via another image viewing app
Allow user to do the following : 
- User can view images in `some` application & click on share option
- Our application should appear as an option to `Convert to PDF`
- On clicking this, our `PDF Converter` app should open up on home page with those images selected. ( A message should appear saying that those images are already added & user can just click on `Create PDF` and PDF will be created)

### PR DESCRIPTION
**Pull request by ac491**
# Description
 fix #131 catch files shared by other apps.
It works for gallery and google photos.
for whatsapp it toasts an error message.

Fixes #(issue)

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [ ] `./gradlew checkstyle`

# Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

### CODE REVIEW

**Comment by Swati4star** [comment]
@ac491 Checks are failing

File: app/src/main/java/swati4star/createpdf/util/FileUtils.java [hunk 1]
```diff
@@ -378,4 +386,268 @@ public static int checkRepeat(String finalOutputFile, final ArrayList<File> mFil
...
         return append;
     }
+
+    /**
+     * Get uri related content real local file path.
+     * @param ctx - context of the activity/fragment
+     * @param uri - uri of the image
+     * @return  - real path of the image file on device
+     */
+    public String getUriRealPath(Context ctx, Uri uri)
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/FileUtils.java]: We don't need the context again. We already have `mContext` above.

File: app/src/main/java/swati4star/createpdf/util/FileUtils.java [hunk 2]
```diff
@@ -378,4 +386,268 @@ public static int checkRepeat(String finalOutputFile, final ArrayList<File> mFil
...
+            } else {
+                // Android OS below sdk version 19
+                ret = getImageRealPath(mContentResolver, uri, null);
+            }
+        }
+
+        return ret;
+    }
+
+    private String getUriRealPathAboveKitkat(Context ctx, Uri uri)
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/FileUtils.java]: add comment here also for this function. We won't need context here also.

File: app/src/main/java/swati4star/createpdf/util/FileUtils.java [hunk 3]
```diff
@@ -378,4 +386,268 @@ public static int checkRepeat(String finalOutputFile, final ArrayList<File> mFil
...
+                        }
+                    }
+                }
+            }
+        }
+
+        return ret;
+    }
+
+    /* Check whether current android os version is bigger than kitkat or not. */
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/FileUtils.java]: The comments format is not consistent in this file. USe javadoc type comments only.

File: app/src/main/java/swati4star/createpdf/activity/MainActivity.java [hunk 4]
```diff
@@ -64,6 +68,39 @@ protected void onCreate(Bundle savedInstanceState) {
...
+                handleSendMultipleImages(intent,fragment); // Handle multiple images
+            }
+        } else if (Intent.ACTION_SEND.equals(action) && type != null) {
+            if (type.startsWith("image/")) {
+                handleSendImage(intent,fragment); // Handle single image
+            }
+        }
+    }
+
+    private void handleSendImage(Intent intent, Fragment fragment) {
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/activity/MainActivity.java]: add comments to this function

**Comment by Swati4star** [comment]
@ac491 Build and checkstyle, both are failing.
