### PR TITLE
fixed issue #283

### LINKED ISSUE #283: Open PDF files when it is selected in history section
### Steps
Go to `History` from the navigation drawer

### Expected behaviour
- When user clicks on any list item, open up the PDF (if it exists, else show a snackbar with text `The PDF doesn't exist`)

### PR DESCRIPTION
**Pull request by vyankatesh24**
# Description

open pdf when selected in history fragment.
image

image

Fixes #283

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/fragment/HistoryFragment.java [hunk 1]
```diff
@@ -106,6 +110,19 @@ public void loadHome() {
         fragmentManager.beginTransaction().replace(R.id.content, fragment).commit();
     }
 
+    @Override
+    public void onItemClick(String path) {
+        FileUtils fileUtils=new FileUtils(mActivity);
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/HistoryFragment.java]: add space before & after =

The checks will fail
