### PR TITLE
Fix #678

### LINKED ISSUE #678: [Split PDF] PDF is getting created even when there is one page in PDF
In `Split PDF` PDF is getting created even when there is one page in PDF.

### Steps to reproduce
* Open `Split PDF`
* Select PDF (Which has only one page)
* Click `Split PDF` button.

### Actual behaviour
New PDF gets created with by suffixing `_1` to it's name.

### Expected behaviour
New PDF shouldn't be created and some warning message must be displayed

### PR DESCRIPTION
**Pull request by piedcipher**
# Description

PDF with only 1 page can't be split & a message in shown when user tries to do the same.

**Demo**

Fixes #678

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/fragment/SplitFilesFragment.java [hunk 1]
```diff
@@ -130,6 +130,10 @@ public void parse() {
         ArrayList<String> outputFilePaths = mPDFUtils.splitPDFByConfig(mPath,
                 mSplitConfitEditText.getText().toString());
         int numberOfPages = outputFilePaths.size();
+        if (numberOfPages == 1) {
+            showSnackbar(getActivity(), "Selected PDF can\'t be split because it has only 1 page!");
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/fragment/SplitFilesFragment.java]: Store this message as a string resource so that it can be translated for other languages.

Comment (piedcipher) [reply app/src/main/java/swati4star/createpdf/fragment/SplitFilesFragment.java]: Done :heavy_check_mark:

**Comment by piedcipher** [comment]
> @piedcipher
> Will it be possible to show a message as soon as the PDF is selected?
> Also, keep on `Split PDF` click which you have implemented.

:cool: :+1:

**Comment by piedcipher** [comment]
> @piedcipher
> Will it be possible to show a message as soon as the PDF is selected?
> Also, keep on `Split PDF` click which you have implemented.

Done :heavy_check_mark:

**Comment by vyankatesh24** [comment]
@piedcipher 
Actually, I have merged this PR and again reverted. As there is one change needed add string `split_one_page_pdf_alert` to all string locale files. I have reverted beacuse it creates problem while creating release APK.

Open new PR with existing and newly asked changes.

**Comment by piedcipher** [comment]
Sure ✅
