### PR TITLE
Fixes ANR in Viewed Files, Checking PDF encryption status on background thread

### LINKED ISSUE #454: [Crash] Input dispatching timed out
### Crash log

I received this crash log in playstore reports. I don't know how this issue can be reproduced looking at the logs. If someone can help with this, it would be great. 💯 

```
Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 7. Wait queue head age: 5834.8ms.)

swati4star.createpdf.activity.MainActivity
```

```
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x729a5ef0 self=0x6fb8ac3a00
  | sysTid=25448 nice=-10 cgrp=default sched=0/0 handle=0x703d8369a8
  | state=S schedstat=( 3870887429 328395255 23047 ) utm=95 stm=292 core=4 HZ=100
  | stack=0x7fd0331000-0x7fd0333000 stackSize=8MB
  | held mutexes=
  #00  pc 000000000001dc6c  /system/lib64/libc.so (syscall+28)
  #01  pc 00000000000e7030  /system/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+152)
  #02  pc 000000000034535c  /system/lib64/libart.so (art::JNI::CallObjectMethod(_JNIEnv*, _jobject*, _jmethodID*, ...)+552)
  #03  pc 00000000000ea9b8  /system/lib64/libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long, int, unsigned int)+48)
  #04  pc 0000000000044490  /system/lib64/libandroidfw.so (android::DisplayEventDispatcher::handleEvent(int, int, void*)+164)
  #05  pc 0000000000015fd0  /system/lib64/libutils.so (android::Looper::pollInner(int)+856)
  #06  pc 0000000000015bf0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+108)
  #07  pc 0000000000111960  /system/lib64/libandroid_runtime.so (???)
  #08  pc 00000000001ea9ac  /system/framework/arm64/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+140)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:325)
  at android.os.Looper.loop (Looper.java:142)
  at android.app.ActivityThread.main (ActivityThread.java:6753)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:482)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```
```
"main" tid=1 Runnable 
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x75ad4370 self=0x4b1c23fa00
  | sysTid=24827 nice=-10 cgrp=default sched=0/0 handle=0x4b20406a98
  | state=R schedstat=( 0 0 0 ) utm=20160 stm=4199 core=4 HZ=100
  | stack=0x5c2a78e000-0x5c2a790000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  at java.util.ArrayList.get (ArrayList.java:410)
  at com.itextpdf.text.pdf.PdfReader.removeUnusedNode (PdfReader.java:3444)
  at com.itextpdf.text.pdf.PdfReader.removeUnusedObjects (PdfReader.java:3492)
  at com.itextpdf.text.pdf.PdfReader.readPdf (PdfReader.java:771)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:198)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:236)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:224)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:214)
  at swati4star.createpdf.util.PDFUtils.isPDFEncrypted (PDFUtils.java:177)
  at swati4star.createpdf.adapter.ViewFilesAdapter.onBindViewHolder (ViewFilesAdapter.java:102)
  at swati4star.createpdf.adapter.ViewFilesAdapter.onBindViewHolder (ViewFilesAdapter.java:49)
  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:6673)
  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:6714)
  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:5647)
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:5913)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5752)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5748)
  at android.support.v7.widget.LinearLayoutManager$LayoutState.next (LinearLayoutManager.java:2232)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk (LinearLayoutManager.java:1559)
  at android.support.v7.widget.LinearLayoutManager.fill (LinearLayoutManager.java:1519)
  at android.support.v7.widget.LinearLayoutManager.scrollBy (LinearLayoutManager.java:1333)
  at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy (LinearLayoutManager.java:1077)
  at android.support.v7.widget.RecyclerView.scrollByInternal (RecyclerView.java:1815)
  at android.support.v7.widget.RecyclerView.onTouchEvent (RecyclerView.java:3076)
  at android.view.View.dispatchTouchEvent (View.java:10040)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2816)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2497)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2822)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2511)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:415)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1808)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3231)
  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:68)
  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:68)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:376)
  at android.view.View.dispatchPointerEvent (View.java:10316)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4530)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4376)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3904)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3957)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3923)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4050)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3931)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4107)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3904)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3957)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3923)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3931)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3904)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6849)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6823)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6784)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6982)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
  at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents (Native method)
  at android.view.InputEventReceiver.consumeBatchedInputEvents (InputEventReceiver.java:176)
  at android.view.ViewRootImpl.doConsumeBatchedInput (ViewRootImpl.java:6950)
  at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run (ViewRootImpl.java:7007)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:952)
  at android.view.Choreographer.doCallbacks (Choreographer.java:752)
  at android.view.Choreographer.doFrame (Choreographer.java:665)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:935)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6124)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:926)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:788)
```

```

"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x75ad4370 self=0x4b1c23fa00
  | sysTid=31946 nice=-10 cgrp=default sched=0/0 handle=0x4b20406a98
  | state=R schedstat=( 0 0 0 ) utm=828 stm=65 core=0 HZ=100
  | stack=0x5c2a78e000-0x5c2a790000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  #00  pc 0000000000479994  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
  #01  pc 0000000000479990  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
  #02  pc 000000000044dfa0  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+472)
  #03  pc 00000000004658fc  /system/lib64/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+820)
  #04  pc 000000000044eeac  /system/lib64/libart.so (_ZN3art6Thread21RunCheckpointFunctionEv+192)
  #05  pc 0000000000547b08  /system/lib64/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE+100)
  #06  pc 0000000000547a60  /system/lib64/libart.so (_ZN3art12JniMethodEndEjPNS_6ThreadE+28)
  #07  pc 00000000000aeb3c  /system/framework/arm64/boot.oat (Java_java_lang_System_arraycopy__Ljava_lang_Object_2ILjava_lang_Object_2II+216)
  at java.lang.System.arraycopy! (Native method)
  at com.itextpdf.text.pdf.ByteBuffer.toByteArray (ByteBuffer.java:561)
  at com.itextpdf.text.pdf.PdfName.encodeName (PdfName.java:2587)
  at com.itextpdf.text.pdf.PdfName.<init> (PdfName.java:2465)
  at com.itextpdf.text.pdf.PdfReader.readDictionary (PdfReader.java:1915)
  at com.itextpdf.text.pdf.PdfReader.readPRObject (PdfReader.java:1952)
  at com.itextpdf.text.pdf.PdfReader.readObjStm (PdfReader.java:1581)
  at com.itextpdf.text.pdf.PdfReader.readDocObj (PdfReader.java:1474)
  at com.itextpdf.text.pdf.PdfReader.readPdf (PdfReader.java:751)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:198)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:236)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:224)
  at com.itextpdf.text.pdf.PdfReader.<init> (PdfReader.java:214)
  at swati4star.createpdf.util.PDFUtils.isPDFEncrypted (PDFUtils.java:177)
  at swati4star.createpdf.adapter.ViewFilesAdapter.onBindViewHolder (ViewFilesAdapter.java:102)
  at swati4star.createpdf.adapter.ViewFilesAdapter.onBindViewHolder (ViewFilesAdapter.java:49)
  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:6673)
  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:6714)
  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:5647)
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:5913)
  at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline (GapWorker.java:285)
  at android.support.v7.widget.GapWorker.flushTaskWithDeadline (GapWorker.java:342)
  at android.support.v7.widget.GapWorker.flushTasksWithDeadline (GapWorker.java:358)
  at android.support.v7.widget.GapWorker.prefetch (GapWorker.java:365)
  at android.support.v7.widget.GapWorker.run (GapWorker.java:396)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6124)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:926)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:788)
```

### PR DESCRIPTION
**Pull request by mohammaduvez**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
If there are any UI change, please include the screenshots also.

- Checking PDF encryption status on background thread
- Added `PDFFile` Model to store encryption status of PDF file

Fixes #454

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [ ] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/adapter/ViewFilesAdapter.java [hunk 1]
```diff
@@ -269,23 +279,22 @@ private void deleteFile(String name, int position) {
...
-                        public void onDismissed(Snackbar snackbar, int event) {
-                            if (undoClicked.get() == 0) {
-                            fdelete.delete();
-                            mDatabaseHelper.insertRecord(fdelete.getAbsolutePath(),
-                                    mActivity.getString(R.string.deleted));
-                            }
-                    }
-                }).show();
+        getSnackbarwithAction(mActivity, R.string.snackbar_file_deleted).setAction(R.string.snackbar_undoAction, v -> {
+            if (mFileList.size() == 0) {
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/adapter/ViewFilesAdapter.java]: i dont see any change in this block of code, only spaces
please revet it

File: app/src/main/java/swati4star/createpdf/util/PDFEncryptionUtility.java [hunk 2]
```diff
@@ -67,7 +63,8 @@ public void setPassword(final String filePath, final DataSetChanged dataSetChang
         mPasswordInput.addTextChangedListener(
                 new TextWatcher() {
                     @Override
-                    public void beforeTextChanged(CharSequence s, int start, int count, int after) { }
+                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/PDFEncryptionUtility.java]: why this change

File: app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java [hunk 3]
```diff
@@ -46,7 +44,45 @@ public WatermarkUtils(Activity context) {
         mFileUtils = new FileUtils(context);
     }
 
-    public void setWatermark(String path, final DataSetChanged dataSetChanged, final ArrayList<File> mFileList) {
+    public static int getStyleValueFromName(String name) {
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java]: why this refator

File: app/src/main/java/swati4star/createpdf/adapter/ViewFilesAdapter.java (hunk 1 above)
Comment (mohammaduvez) [reply app/src/main/java/swati4star/createpdf/adapter/ViewFilesAdapter.java]: because app:checkstyle fails and can't build the project

File: app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java (hunk 3 above)
Comment (mohammaduvez) [reply app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java]: reverted

File: app/src/main/java/swati4star/createpdf/util/PDFEncryptionUtility.java (hunk 2 above)
Comment (mohammaduvez) [reply app/src/main/java/swati4star/createpdf/util/PDFEncryptionUtility.java]: reverted

**Comment by Swati4star** [comment]
Awesome @mohammaduvez 👍
