### PR TITLE
button click bug fix

### LINKED ISSUE #662: bug in text to pdf "create PDF" button
create PDF button won't work when you click on it the first time

### Steps to reproduce

- open TEXT to PDF fragment
- select a text file
- now click on create PDF
- **nothing will happen**
- click on it again and then name of new file will be asked

### Expected behaviour
create pdf dilaog where we enter the file name should be opened when we click on **create PDF** the first time. but because of some weird reason, it doesn't. I still need to figure out why

### Would you like to work on the issue?
yes

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description
create PDF button is now working fine. 

Fixes #662 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ni3verma** [comment]
Bug was because mPermissionGranted was not initialized properly.
@sidhuparas @vyankatesh24 
as PermissionUtils class is still not merged so I have to duplicate my code. So merge this code before merging permissionUtilities PR.

File: app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java [hunk 1]
```diff
@@ -504,4 +505,16 @@ private void getRuntimePermissions() {
...
+    private boolean isPermissionGranted() {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
+            if ((ContextCompat.checkSelfPermission(mActivity, Manifest.permission.WRITE_EXTERNAL_STORAGE)
+                    != PackageManager.PERMISSION_GRANTED) &&
+                    (ContextCompat.checkSelfPermission(mActivity, Manifest.permission.READ_EXTERNAL_STORAGE)
+                            != PackageManager.PERMISSION_GRANTED)) {
+                return false;
+            }
+        }
+        return true;
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: I would suggest you put this PR on hold since there is another PR which is adding a permission utils file in the project. After that PR is merged, you can use that utility class to check for permissions.

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: that PR is still not approved by anyone. that's why I am saying to merge it first and then jddeep can fetch changes from main and use pemissionUtils function here also.
or maybe you can do the opposite, however you like.

Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: that PR has been merged. You can do the required changes now

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: sure

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: @Swati4star

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: @Swati4star

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: @Swati4star 
PermissionUtils class contains no method through which we can check if permission is already granted or not.(required in this case)
and what is the point of **checkRuntimePermissions** method returning true? it will return true only when `Build.VERSION.SDK_INT < Build.VERSION_CODES.M`
further ZipToPdfFragment still contains permission related code.
I don't understand why that PR was merged

Comment (sidhuparas) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: @Ni3verma You can create an issue regarding that. For your second query: https://github.com/Swati4star/Images-to-PDF/pull/656#discussion_r269386181

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: @Swati4star please merge it as permissionUtils class is of no use here. and make a separate issue to fix permissionUtils and use it in ZipToPdfFragment and TextToPdfFragment

**Comment by vyankatesh24** [comment]
@sidhuparas 
Can this be merged?

**Comment by sidhuparas** [comment]
@vyankatesh24 PermissionsUtils improvements are required. I think we can merge this code and @Ni3verma while making PR for the #669, use PermissionsUtils in this PR's code as well where required.
