### PR TITLE
fixes for #137

### LINKED ISSUE #137: Show conversions history
- Add a new option in the navigation bar `History`
- It should have the following type of operations performed by the user in chronological order : 
     - PDF created
     - PDF renamed
     - PDF deleted
     - PDF printed
     In each time, show the name of the PDF & the date when the operation was performed.
- Add an option on the action bar to delete this history also. ( Add a confirmation dialog )

**How to do?**
Maintain a database of the operations performed by the user. Whenever user do any of the above operation, add it to that database.

### PR DESCRIPTION
**Pull request by vyankatesh24**
# Description
added new feature "View conversion History"

image

image

image

Fixes #137 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/fragment/HistoryFragment.java [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+                deleteHistory();
+                break;
+        }
+        return super.onOptionsItemSelected(item);
+    }
+
+    private void deleteHistory() {
+        new MaterialDialog.Builder(mActivity)
+                .title(R.string.warning)
+                .content("Are you sure you want to delete history ?")
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/HistoryFragment.java]: add this constant string to strings.xml file

File: app/src/main/java/swati4star/createpdf/fragment/HistoryFragment.java [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+import swati4star.createpdf.database.AppDatabase;
+import swati4star.createpdf.database.History;
+import swati4star.createpdf.util.ViewFilesDividerItemDecoration;
+
+public class HistoryFragment extends Fragment {
+
+    @BindView(R.id.getStarted)
+    Button getStarted;
+    @BindView(R.id.emptyStatusView)
+    ConstraintLayout mConstraintLayout;
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/HistoryFragment.java]: change the name from `mConstraintLayout` to `mEmptyStatusLayout`
