### PR TITLE
Fix #670

### LINKED ISSUE #670: Add an action to snackbar to view created PDF in Add Watermark
### Description
When we add watermark to PDF the Snackbar shows `Watermark Added` but does not show `View` action.

### Steps to reproduce
* View Files
* Click on PDF the dialog will open
* Select Add Watermark
* Enter text and click `Ok`

### Expected behavior
The snackbar should show  `View` action and on Clicking it the PDF should be Displayed.

### Actual behavior
Snackbar does not show `View` action.

### PR DESCRIPTION
**Pull request by piedcipher**
# Description

- Added SnackBar with Action to view PDF created using "Add Watermark" option in `ImageToPdfFragment`.

## Demo

Fixes #670

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by piedcipher** [comment]
Thank you @sidhuparas :smile: :+1:

File: app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java [hunk 1]
```diff
@@ -116,9 +117,11 @@ public void afterTextChanged(Editable input) {
                         Color.blue(colorPickerInput.getColor()),
                         Color.alpha(colorPickerInput.getColor())
                 )));
-                createWatermark(path);
+                String output = createWatermark(path);
```
Comment (vyankatesh24) [inline app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java]: @piedcipher 
Just a little change 'output' to something related the function is returning.
I think it is will be path if so change it to `filePath` or something

Comment (piedcipher) [reply app/src/main/java/swati4star/createpdf/util/WatermarkUtils.java]: Done.
