### PR TITLE
Fix #613 Wrong display of snackbar showing rearrange image

### LINKED ISSUE #613: Wrong display of snackbar showing rearrange image
Snackbar shows images are rearranged even if they are not rearranged.

### Steps to reproduce
1.Select Images to PDF
2.Select Images
3.Select 2-3 images and click sure
4.Click Rearrange images and just press back button

### Actual behaviour
Snackbar displays images are rearranged although it is not arranged

### Expected behaviour
Message should be displayed only if images are rearranged

### Would you like to work on the issue?
Yes

### PR DESCRIPTION
**Pull request by theabhishekavi**
Fixes #613 

- [x] Bug fix (non-breaking change which fixes an issue)

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by theabhishekavi** [comment]
@Swati4star @sidhuparas kindly review

**Comment by theabhishekavi** [comment]
Thanks for the quick replies and helpful changes. @sidhuparas

File: app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java [hunk 1]
```diff
@@ -370,9 +373,12 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
...
             case INTENT_REQUEST_REARRANGE_IMAGE:
                 mImagesUri = data.getStringArrayListExtra(RESULT);
-                if (mImagesUri.size() > 0) {
+                if (!mUnarrangedImagesUri.equals(mImagesUri) && mImagesUri.size() > 0) {
                     showSnackbar(mActivity, R.string.images_rearranged);
-                } else {
+                    mUnarrangedImagesUri.clear();
+                    mUnarrangedImagesUri.addAll(mImagesUri);
+                }
+                if (mImagesUri.size() == 0) {
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: I think you can move this `if` block inside the `else` block since `mImagesUri` will only be empty in the `else` block.

Comment (theabhishekavi) [reply app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: if we move the if block inside the else block then when images are not arranged the else block will be executed causing the Create pdf button to disable

Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: Do we need `mImagesUri.size() > 0` check here?

File: app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java [hunk 2]
```diff
@@ -370,9 +373,12 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
 
             case INTENT_REQUEST_REARRANGE_IMAGE:
                 mImagesUri = data.getStringArrayListExtra(RESULT);
-                if (mImagesUri.size() > 0) {
+                if (!mUnarrangedImagesUri.equals(mImagesUri) && mImagesUri.size() > 0) {
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: Do we need `mImagesUri.size() > 0` check here?

**Comment by Swati4star** [comment]
Looks good! Congrats on your first contribution to this project 👍
