### PR TITLE
Fix "No PDFs to Show" not disappearing

### LINKED ISSUE #899: "No PDFs to show" message should disappear
When I'm searching for files in the "View Files" option, if I search for something that is not a pdf file the "No PDFs to show" message appears, it should disappear after searching for a valid pdf file.

### Steps to reproduce
Go to "View Files"
Search for an unexisting name of a PDF file
Search for an existing name of a PDF File

### Expected behaviour
Pop-up should disappear and files shown

### Actual behaviour
Pop-up doesn't disappear but files are shown

### Would you like to work on the issue?
Yes

### PR DESCRIPTION
**Pull request by guicoliv**
# Description
Added a call in the populateViewList method to set the empty stage message visibility to gone when the search has matches after not having matches.
Also, send an empty response for the setData method for the files in the list view to disappear when there are no matches

Fixes #899

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [X] `./gradlew assembleDebug assembleRelease`
- [X] `./gradlew checkstyle`

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/util/PopulateList.java [hunk 1]
```diff
@@ -69,7 +69,9 @@ private void populateListView() {
             mHandler.post(mEmptyStateChangeListener::showNoPermissionsView);
         else if (pdfFiles.size() == 0) {
             mHandler.post(mEmptyStateChangeListener::setEmptyStateVisible);
+            mHandler.post(() -> mAdapter.setData(null));
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/PopulateList.java:72]: This is also going to affect when there are no PDFs to show initially also

Comment (guicoliv) [reply app/src/main/java/swati4star/createpdf/util/PopulateList.java:72]: I tried this, the behavior when there are no PDFs initially remains the same, the message shows up, same thing if you delete all the pdfs
