### PR TITLE
Remove and Reorder pages bug solved

### LINKED ISSUE #683: Bug in Remove Pages
### Steps to reproduce
* Remove Pages
* Select PDF
* Click `Create PDF`
* Click `back` (New File gets created even if we don't change the order of pages or delete pages.)
* Select New File using `Bottom Sheet`. (`View PDF` button remains visible after selecting the next pdf.)

### Expected behaviour
* New File shouldn't get created even if we don't change the order of pages or remove pages.
* `View PDF` should become invisible after selecting next pdf.

### Actual behaviour
* New File gets created even if we don't change the order of pages or delete pages.
* `View PDF` button remains visible after selecting the next pdf.

### PR DESCRIPTION
**Pull request by rob729**
# Description
- New PDF does not get created if no chnages are made to the file.
- View PDF is not shown if new file is selected.
2xtkx0 

Fixes #683, #663 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rob729** [comment]
@vyankatesh24  Please review this PR.

File: app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java [hunk 1]
```diff
@@ -154,5 +161,19 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+//        if (mInitialSequence.size() == mSequence.size()) {
+//            while (i < mSequence.size()) {
+//                if (!(mInitialSequence.get(i).equals(mSequence.get(i))))
+//                    mSameSize = false;
+//            }
+//        } else {
+//            mSameSize = false;
+//        }
+//        return mSameSize;
+//    }
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: Why is this commented out?

File: app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java [hunk 2]
```diff
@@ -130,6 +134,9 @@ private void passUris() {
         for ( int x : mSequence)
             result.append(x).append(",");
         returnIntent.putExtra(RESULT, result.toString());
+        boolean sameFile = mInitialSequence.equals(mSequence);
+        Log.e("TAG", "" + mInitialSequence + ":" + mSequence + ":" + sameFile);
+        returnIntent.putExtra("SameFile", sameFile);
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: Make "SameFile" into a constant string. For eg. check line 136(RESULT).

**Comment by rob729** [comment]
@srv-twry I have made the requested changes.
Please review the PR again.

File: app/src/main/java/swati4star/createpdf/fragment/RemovePagesFragment.java [hunk 3]
```diff
@@ -160,7 +161,12 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) throw
             }
 
             if (mPDFUtils.reorderRemovePDF(mPath, outputPath, pages)) {
-                viewPdfButton(outputPath);
+                if (sameFile) {
```
Comment (vyankatesh24) [inline app/src/main/java/swati4star/createpdf/fragment/RemovePagesFragment.java]: There is `ArrayList<Bitmap> bitmaps = new ArrayList<>();` in this file.
Can't this be used for comparison rather than this approach?

File: app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java [hunk 4]
```diff
@@ -72,8 +75,10 @@ private void initRecyclerView(ArrayList<Bitmap> images) {
         mRearrangeImagesAdapter = new RearrangePdfAdapter(this, images, this);
         recyclerView.setAdapter(mRearrangeImagesAdapter);
         mSequence = new ArrayList<>();
-        for ( int i = 0; i < images.size(); i++)
+        for ( int i = 0; i < images.size(); i++) {
             mSequence.add(i + 1);
+        }
+        mInitialSequence.addAll(mSequence);
```
Comment (vyankatesh24) [inline app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: There is `ArrayList<Bitmap> bitmaps = new ArrayList<>();` in `RemovePagesFragment` file.
Can't this be used for comparison rather than this approach?
See line 203 in `RemovePagesFragment`

File: app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java [hunk 5]
```diff
@@ -130,6 +135,9 @@ private void passUris() {
         for ( int x : mSequence)
             result.append(x).append(",");
         returnIntent.putExtra(RESULT, result.toString());
+        boolean sameFile = mInitialSequence.equals(mSequence);
+        Log.e("TAG", "" + mInitialSequence + ":" + mSequence + ":" + sameFile);
```
Comment (vyankatesh24) [inline app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: Remove all log related statements.

File: app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java (hunk 4 above)
Comment (rob729) [reply app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: @vyankatesh24 What is the advantage of this approach above the implemented one?

Comment (vyankatesh24) [reply app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: As ArrayList is already present there. you can directly compare rather this overhead of creating a new one and then comparing.

Comment (rob729) [reply app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: But the bitsmap is present in different activity so we will have to send it as an intent to the RearrangePdfPages activity and it can cause a problem if pdf size is large.

Comment (vyankatesh24) [reply app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: Ok, then let your approach be as it is.
Make other suggested changes :+1:

Comment (rob729) [reply app/src/main/java/swati4star/createpdf/activity/RearrangePdfPages.java]: Ok 
Thanks

**Comment by rob729** [comment]
@vyankatesh24 I have done the requested changes.
