### PR TITLE
Fixed the Freeze of UI while ExceltoPDF converts

### LINKED ISSUE #707: v8.6.4 freezes while converting from Excel to pdf
#### Expected behavior
I excepted th Excel to Pdf tool to succefully convert excel file without freezing the device.

#### Actual behavior
PDF Converter v8.6.3 freezes the device, and crashed the device. While v8.6.4 only freezes the device during conversion.

#### How to reproduce
- Lunch PDF Converter v8.6.3, or v8.6.4
- locate excel to pdf tool
- select the execel file that is needed to be converted
- click on excel to pdf, and set the file name
- click on okay, and watch it freeze. (v8.6.3 crashes, v8.6.4 freezes during the conversion process, then back to normal after converting)

* Browser/App version:
Android 8.1

### PR DESCRIPTION
**Pull request by jddeep**
# Description
Fixed the Freeze of UI while ExceltoPDF converts

Fixes #707 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 Please review and merge. Thanks.

**Comment by Swati4star** [comment]
- Show some UI while this is being done in the bakcground (that's why I made this issue medium)
- we do show an animation dialog in case of converting images to PDF too.

**Comment by jddeep** [comment]
> * Show some UI while this is being done in the bakcground (that's why I made this issue medium)
> * we do show an animation dialog in case of converting images to PDF too.

Sure thing @Swati4star 👍

**Comment by jddeep** [comment]
> * Show some UI while this is being done in the bakcground (that's why I made this issue medium)
> * we do show an animation dialog in case of converting images to PDF too.

@Swati4star I could not find the initialization and usage of the lottie animation in the `ImageToPdf` Fragment, though it shows up in the actual working of the app. Can you give me some clue as to where that can be found?

**Comment by Swati4star** [comment]
This might help
https://github.com/Swati4star/Images-to-PDF/blob/master/app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java#L748
https://github.com/Swati4star/Images-to-PDF/blob/9862da31b9e4061f6c6d0b2081317a99045f183e/app/src/main/java/swati4star/createpdf/util/DialogUtils.java#L79

**Comment by jddeep** [comment]
Alright @Swati4star Will have a look.

**Comment by jddeep** [comment]
@Swati4star Done. Please review, Thank you.

File: app/src/main/java/swati4star/createpdf/fragment/ExceltoPdfFragment.java [hunk 1]
```diff
@@ -190,23 +193,36 @@ private void convertToPdf(String mFilename) {
...
-            showSnackbar(mActivity, R.string.error_occurred);
-        } finally {
-            mMorphButtonUtility.morphToGrey(mCreateExcelPdf, mMorphButtonUtility.integer());
-            mCreateExcelPdf.setEnabled(false);
-            mExcelFileUri = null;
-        }
+        mMaterialDialog = createAnimationDialog(mActivity);
+        mMaterialDialog.show();
+
+        new AsyncTask() {
```
Comment (vyankatesh24) [inline app/src/main/java/swati4star/createpdf/fragment/ExceltoPdfFragment.java]: I think it will be better if you do create a new class by extending `AsyncTask`. And call that here.
What do you think @Swati4star?

Comment (jddeep) [reply app/src/main/java/swati4star/createpdf/fragment/ExceltoPdfFragment.java]: Alright @vyankatesh24 Will be doing that.

Comment (jddeep) [reply app/src/main/java/swati4star/createpdf/fragment/ExceltoPdfFragment.java]: @vyankatesh24 But then it will be difficult to handle the `onPostExecute tasks like setting the morphingButton to false, nullifying the uri, paths, the other animators, etc.

Comment (vyankatesh24) [reply app/src/main/java/swati4star/createpdf/fragment/ExceltoPdfFragment.java]: > @vyankatesh24 But then it will be difficult to handle the `onPostExecute` tasks like setting the morphingButton to false, nullifying the uri, paths, the other animators, toggling the Dialog animation, etc.

@jddeep 
I think there will not be any problem if you create a class in the same file. But wait let @Swati4star reply.

Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/fragment/ExceltoPdfFragment.java]: There wont be any difficulty in handling the postexecution too. You can look into ImageToPdfFragment.java also. We created a new interface `OnPDFCreatedInterface` and we send out an instance. Look at that workflow, if you find some difficulty there, let me know.

It'll be better to move the code to a different class only.

**Comment by jddeep** [comment]
@Swati4star @vyankatesh24 Changes made. Please review.

File: app/src/main/java/swati4star/createpdf/util/ExcelToPDFAsync.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+import com.aspose.cells.Workbook;
+import swati4star.createpdf.interfaces.OnPDFCreatedInterface;
+
+public class ExcelToPDFAsync extends AsyncTask<Void, Void, Void> {
+    private final OnPDFCreatedInterface mOnPDFCreatedInterface;
+    private boolean mSuccess;
+    private String mPath;
+    private String mDestPath;
+
+    public ExcelToPDFAsync(String parentPath, String destPath,
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/util/ExcelToPDFAsync.java]: add comments

**Comment by jddeep** [comment]
@Swati4star comments added!

File: app/src/main/java/swati4star/createpdf/util/ExcelToPDFAsync.java (hunk 2 above)
Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/util/ExcelToPDFAsync.java]: you are supposed to describe each parameter too

Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/util/ExcelToPDFAsync.java]: and why are we taking `parentPath` as parameter. It is not even being used anywhere

**Comment by jddeep** [comment]
@Swati4star params described.
