### PR TITLE
permission bug fix

### LINKED ISSUE #669: PermissionsUtils Improvements
A new method is required in `PermissionsUtils` class and some minor refactors are required.

## Bug Fix
After the implementation of `PermissionsUtils` class, `onRequestPermissionsResult()` is not getting executed in Fragment class. There's a workaround though.

- Modify the existing method as:
``` 
public static void requestRuntimePermissions(Object context, List<String> permissions,
                                                 int requestCode) {
        if (context instanceof Activity) {
            ActivityCompat.requestPermissions(((AppCompatActivity) context),
                    permissions.toArray(new String[permissions.size()]), requestCode);
        } else if (context instanceof Fragment) {
            ((Fragment) context).requestPermissions(permissions.toArray(new String[permissions.size()]),
                    requestCode);
        }
    }
```

- Introduce the new method:
```
 private static Context retrieveContext(Object context) {
        if (context instanceof AppCompatActivity)
            return ((AppCompatActivity) context).getApplicationContext();
        else
            return ((Fragment) context).requireActivity();
    }
```
- Use it wherever necessary like this:
`                if ((ContextCompat.checkSelfPermission(retrieveContext(context),...`
- Modify the function arguments as required for `checkRuntimePermissions()` to use `Object` instead of `Activity` as first argument.
- Update Javadoc comments.

## Other Requirements
- Merge `checkRuntimePermissions()` and `requestRuntimePermissions()` methods (latter into former)
- Refactor `checkRuntimePermissions()` to `requestRuntimePermissions()`
- Create a new method `checkRuntimePermissions()` which returns `true` if the permission is granted and `false` if not.
- Modify Javadoc comments as required.
- Use PermissionsUtils in `ZipToPdfFragment` and `TextToPdfFragment`  

If you are confused by above points, read them in order from top to bottom.

### Would you like to work on the issue?
Tell us if you would like to work on this issue

Thanks to @Ni3verma for pointing it out. Since you have pointed it out, you are given a preference if you want to work on this issue.

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description
corrected permission Utils class and it's uses
Uses PermissionsUtils in ZipToPdfFragment and TextToPdfFragment

Fixes #669 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ni3verma** [comment]
@Swati4star @vyankatesh24 please review

File: app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java [hunk 1]
```diff
@@ -1,63 +1,62 @@
...
-                permissions.toArray(new String[permissions.size()]), requestCode);
+        if (context instanceof Activity) {
+            ActivityCompat.requestPermissions((AppCompatActivity) context,
+                    permissions, requestCode);
+        } else if (context instanceof Fragment) {
+            ((Fragment) context).requestPermissions(permissions, requestCode);
+        }
+    }
+
+    private static Context retrieveContext(@NonNull Object context) {
```
Comment (sidhuparas) [inline app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java]: Add Javadoc style comments for `retrieveContext()` function.

File: app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java [hunk 2]
```diff
@@ -1,63 +1,62 @@
...
+                    return false;
                 }
             }
-            try {
-                requestRuntimePermissions(activity, listPermissionsNeeded, requestCode);
-                return false;
-            } catch (Exception e) {
-                e.printStackTrace();
-                Log.d(TAG, "Faulty permission passed");
-            }
```
Comment (sidhuparas) [inline app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java]: Implement basic `try-catch` in both the functions because `permission` is being received in `String[]` form which can be anything like "xyz" instead of proper permission `Manifest.permission.xyz`.

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java]: This whole app uses two types of permission
* read, write access
* read, write, camera
and I have made constants for them in `Constant.java

Comment (sidhuparas) [reply app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java]: Then I think you should include this information in `PermissionsUtils` class (probably just above the class name) since new-comers probably won't know the declared arrays in `Constants`.

Comment (sidhuparas) [reply app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java]: Rest changes look good :)

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/util/PermissionsUtils.java]: done

File: app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java [hunk 3]
```diff
@@ -312,10 +314,10 @@ public void onRequestPermissionsResult(int requestCode,
             return;
 
         switch (requestCode) {
-            case PERMISSION_REQUEST_WRITE_EXTERNAL_STORAGE_RESULT: {
+            case REQUEST_PERMISSIONS_CODE: {
                 if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
-                    if (mOpenSelectImages)
-                        selectImages();
+                    mPermissionGranted = true;
+                    selectImages();
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: you have removed the if condition for this case
`if (mOpenSelectImages)`

File: app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java [hunk 4]
```diff
@@ -477,7 +475,7 @@ public void onRequestPermissionsResult(int requestCode,
             case PERMISSION_REQUEST_WRITE_EXTERNAL_STORAGE_RESULT: {
                 if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                     mPermissionGranted = true;
-                    openCreateTextPdf();
+                    selectTextFile();
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: is it also changed by mistake?

File: app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java (hunk 3 above)
Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: yes I have because it's of no use.
earlier we were getting permission from user at two places:
* when we enter ImagesToPdfFragment
* when user click on add images
and this is why mOpenSelectImages was used.
I have removed the code to get permission on  entering ImagesToPdfFragment becuase it's useless, only when user click on add images, he will be asked for permission. so as now we are requesting permission at only one place, mOpenSelectImages  is not required

Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/fragment/ImageToPdfFragment.java]: Okay. Sounds good :)

File: app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java (hunk 4 above)
Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: No, I though about something.
let me think about it :thinking:

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: when user clicks on select images button (selectTextFile() method)
this is the method where we check if user has permission or not.
if he has, then everything will work as normal
if he doesn't have permission, then we will request permission and return from this method and now onRequestPermissionsResult() will be called, if user grants the permission then selectTextFile() method is where we want to get back as earlier we returned from this method immediately after requesting permission.
I hope it's clear

Comment (Swati4star) [reply app/src/main/java/swati4star/createpdf/fragment/TextToPdfFragment.java]: Sure. Makes sense :)
