### PR TITLE
Split PDF history bug fixed

### LINKED ISSUE #757: [Split PDF] History entry not created properly
History entry not created properly.
It gets created in some cases, in some cases, it does not.

### PR DESCRIPTION
**Pull request by rob729**
# Description

Fixes #757

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rob729** [comment]
@vyankatesh24 Please review the PR.

File: app/src/main/java/swati4star/createpdf/util/PDFUtils.java [hunk 1]
```diff
@@ -589,6 +589,8 @@ public boolean reorderRemovePDF(String inputPath, String output, String pages) {
                         copy.addPage(copy.getImportedPage(reader, startPage));
                         document.close();
                         outputPaths.add(fileName);
+                        new DatabaseHelper(mContext).insertRecord(fileName,
```
Comment (vyankatesh24) [inline app/src/main/java/swati4star/createpdf/util/PDFUtils.java]: Rather than duplicating if we put in the ` if (reader.getNumberOfPages() > 1)` 
will not that work ?

Comment (rob729) [reply app/src/main/java/swati4star/createpdf/util/PDFUtils.java]: Yes it will work

**Comment by rob729** [comment]
@vyankatesh24 Please review the change.

**Comment by vyankatesh24** [comment]
Try giving full split range i.e. for 5 pages PDF `1-5`
It creates a history entry, which should not be created as no file gets created in this case.

**Comment by rob729** [comment]
@vyankatesh24 I guess then I should revert the changes. what do you say?

**Comment by vyankatesh24** [comment]
> @vyankatesh24 I guess then I should revert the changes. what do you say?

Sure, Test and then push the changes

Otherwise, If possible try rearranging the if conditions.

**Comment by rob729** [comment]
@vyankatesh24 I have reverted the changes.
