### PR TITLE
nav selected item highlighting

### LINKED ISSUE #618: Navigation Drawer Items doesn't get highlighted.
When we click on any navigation drawer items, Items doesn't get highlighted.

### Steps to reproduce
* Open App
* Navigation Drawer
* Select Any Item (Fragment)

### Expected behaviour
Selected Item should be highlighted.

### Actual behaviour
`Home` remains highlighted always.

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description
navigation drawer item is highlighting whether we click on shortcut on home fragment or click on navigation drawer item.

Fixes #618

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by sidhuparas** [comment]
"Help" and "Share" shouldn't remain selected as they are 1-time actions.

File: app/src/main/java/swati4star/createpdf/activity/MainActivity.java [hunk 1]
```diff
@@ -92,7 +92,7 @@ protected void onCreate(Bundle savedInstanceState) {
 
         // Set navigation drawer
         ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
-                this, drawer, toolbar, R.string.app_name, R.string.app_name);
+                this, drawer, toolbar, R.string.drawer_open, R.string.drawer_close);
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/activity/MainActivity.java]: dont change this

File: app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java [hunk 2]
```diff
@@ -102,125 +100,115 @@ public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
...
 
         Fragment fragment = null;
         FragmentManager fragmentManager = getFragmentManager();
         Bundle bundle = new Bundle();
-        highLightNavigationDrawerItem(v);
 
         switch (v.getId()) {
             case R.id.images_to_pdf:
                 fragment = new ImageToPdfFragment();
+                highLightNavigationDrawerItem(R.id.nav_camera);
```
Comment (Swati4star) [inline app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java]: i didnt want this much code repition, thats why I created a hashmap.
Is it possible to do your changes using a hashmap only?

Comment (sidhuparas) [reply app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java]: Yes, any reason to not use Hashmap? Also refactor `highLightNavigationDrawerItem()` to `highlghtNavigationDrawerItem()`.

**Comment by Ni3verma** [comment]
> "Help" and "Share" shouldn't remain selected as they are 1-time actions.

okay

File: app/src/main/java/swati4star/createpdf/activity/MainActivity.java (hunk 1 above)
Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/activity/MainActivity.java]: why? any reason for this?

File: app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java (hunk 2 above)
Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java]: as now we have divided the xml in groups so 
`mNavigationView.getMenu().getItem(index).setChecked(true);` was not working.
and with ` mNavigationView.setCheckedItem(id);` I need the real id of the nav drawer that is to be highlight not it's index.
so basically now we want home fragment to send the id and not index to main activity so that highlighting is proper

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java]: okay. I'll refractor highLightNavigationDrawerItem() to highlightNavigationDrawerItem().

Comment (Ni3verma) [reply app/src/main/java/swati4star/createpdf/fragment/HomeFragment.java]: or I can make a hashmap from id of clicked view in home fragment to id of nav drawer item.
this could also work

**Comment by Ni3verma** [comment]
help and share button click fix
used sparseIntArray instead of HashMap
refractored the method name
reverted the changes made in ActionBarDrawerToggle constructor

**Comment by Ni3verma** [comment]
PS: It should have been a **medium** difficulty issue :weary: 
I Had to make lot of changes
