### PR TITLE
Fixed view files bug

### LINKED ISSUE #736: Bug in View Files
Count of selected files is not shown every time.

### Steps to reproduce
* View Files
* Select All (count will be shown in action bar)
* Deselect all
* Again Select All (count will not be shown in action bar)

### Expected behaviour
Count of selected files should be shown every time in the action bar.

### Actual behaviour
Count of selected files is not shown every time.

### PR DESCRIPTION
**Pull request by rob729**
# Description

2zlkqt

Fixes #736 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rob729** [comment]
@vyankatesh24 @Swati4star Please review this PR.

**Comment by rob729** [comment]
@sidhuparas I have fixed that issue now. Please review the PR again.

File: app/src/main/java/swati4star/createpdf/adapter/ViewFilesAdapter.java [hunk 1]
```diff
@@ -200,10 +200,7 @@ public void unCheckAll() {
      * Sets the action bar title to app name when all files have been unchecked
      */
     private void updateActionBarTitle() {
-        ActionBar actionBar = ((AppCompatActivity) mActivity).getSupportActionBar();
-        if (actionBar != null) {
-            actionBar.setTitle(R.string.app_name);
-        }
+        mActivity.setTitle(R.string.app_name);
     }
```
Comment (sidhuparas) [inline app/src/main/java/swati4star/createpdf/adapter/ViewFilesAdapter.java]: The fix works fine for me. @Swati4star Just check if those 4 removed lines are required for some other bug fix. I remember pointing you out something like this. Otherwise, it seems fine.
