### PR TITLE
changed isInputValid method

### LINKED ISSUE #603: change isInputValid method in pdfUtils.java
change method to something like this:

```
private boolean isInputValid(String path, String[] ranges) {
        try {
            PdfReader reader = new PdfReader(path);
            int numOfPages = reader.getNumberOfPages();

           return checkRangeValidity(numOfPages, ranges);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

private boolean checkRangeValidity(....) { ... }
```

then it'll be easier to unit test checkRangeValidity (issue #594 )

### PR DESCRIPTION
**Pull request by Ni3verma**
# Description
Changes the method so that it's easy to unit test it
Fixes #603 

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by vyankatesh24** [comment]
@Ni3verma 
Check PR, Travis checks are failing

File: app/src/main/java/swati4star/createpdf/util/PDFUtils.java [hunk 1]
```diff
@@ -578,34 +578,53 @@ public boolean reorderRemovePDF(String inputPath, String output, String pages) {
...
+                    return false;
+                }
+            } else {
+                startPage = Integer.parseInt(range.substring(0, range.indexOf("-")));
+                endPage = Integer.parseInt(range.substring(range.indexOf("-") + 1));
+                if (startPage > numOfPages || endPage > numOfPages) {
+                    showSnackbar(mContext, R.string.error_page_number);
+                    return false;
+                } else if (startPage >= endPage) {
+                    showSnackbar(mContext, R.string.error_page_range);
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/util/PDFUtils.java]: You cannot unit test this if you start showing Snackbar in it. Just create two integer constants.

```Java
public static const int ERROR_PAGE_NUMBER=1;
public static const int ERROR_PAGE_RANGE=2;
```

Now return these integers in respective cases.

File: app/src/main/java/swati4star/createpdf/util/PDFUtils.java [hunk 2]
```diff
@@ -578,34 +578,53 @@ public boolean reorderRemovePDF(String inputPath, String output, String pages) {
...
+                    return false;
                 }
             }
-        } catch (IOException e) {
-            e.printStackTrace();
         }
         return true;
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/util/PDFUtils.java]: return 0 here.

File: app/src/main/java/swati4star/createpdf/util/PDFUtils.java [hunk 3]
```diff
@@ -578,34 +578,53 @@ public boolean reorderRemovePDF(String inputPath, String output, String pages) {
...
-                        return false;
-                    }
+    /**
+     * checks if the user entered split ranges are valid or not
+     *
+     * @param numOfPages total number of pages of pdf
+     * @param ranges     string array that contain page range, can be a single integer or range separated by dash like 2-5
+     * @return true if all ranges are valid, otherwise false
+     */
+    private boolean checkRangeValidity(int numOfPages, String[] ranges) {
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/util/PDFUtils.java]: Make it return int

File: app/src/main/java/swati4star/createpdf/util/PDFUtils.java [hunk 4]
```diff
@@ -578,34 +578,53 @@ public boolean reorderRemovePDF(String inputPath, String output, String pages) {
...
+     * @param ranges string array that contain page range, can be a single integer or range separated by dash like 2-5
+     * @return true if input is valid, otherwise false
+     */
     private boolean isInputValid(String path, String[] ranges) {
         try {
             PdfReader reader = new PdfReader(path);
             int numOfPages = reader.getNumberOfPages();
-            int startPage;
-            int endPage;
+            return checkRangeValidity(numOfPages, ranges);
```
Comment (srv-twry) [inline app/src/main/java/swati4star/createpdf/util/PDFUtils.java]: instead of returning it do it like this.

```Java
int result = checkRangeValidity(numOfPages, ranges);
switch(result) {
    case ERROR_PAGE_NUMBER:
         show snackbar and return false
   case ERROR_PAGE_RANGE:
         show snackbar and return false
   default:
         return true;
}
```

**Comment by Ni3verma** [comment]
@vyankatesh24 travis checks passed :100: 
@sidhuparas corrected the error, thanks :+1: 
@srv-twry Thank you for your detailed suggestions. please review again

**Comment by srv-twry** [comment]
@Ni3verma Hi, so hope you understood why I suggested those changes. A unit test runs on the JVM and hence it should avoid Android SDK usage(otherwise you'll have to mock it). That's why I wanted you to make the `checkRangeValidity` completely free of any Android SDK usage. Now you can very easily pass the arguments in the `checkRangeValidity` method and check if it's output matches with the expected output.

**Comment by Ni3verma** [comment]
@srv-twry yes I got your point.😁
