### PR TITLE
Fixed Merge PDF bug

### LINKED ISSUE #881: "Select Files" button in Merge PDF doesn't work
My cellphone is Android 9.
### Steps to reproduce
1. Click "Merge PDF"
2. Click "SELECT FILES"
3. Select a file from your local file

### Expected behaviour
A file has been added to the list successfully.

### Actual behaviour
The dialog tells me a file has been added to the list successfully. However, the file name is blank. After two files are added, click "MERGE FILES". The dialog tells me "We were unable to access PDF. Files may be encrypted or in the external storage".

### Would you like to work on the issue?
Currently I am working on another project, so I don't have time to work on this issue.

### PR DESCRIPTION
**Pull request by Raj-Datta-Manohar**
# Description

Fixed Merge PDF bug, where there was no check if directory was created or not.  
Added a check for parent directory. 

Fixes #881

## Type of change
Just put an x in the [] which are valid.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
- [x] `./gradlew assembleDebug assembleRelease`
- [x] `./gradlew checkstyle`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/swati4star/createpdf/util/StringUtils.java [hunk 1]
```diff
@@ -68,8 +68,15 @@ public void hideKeyboard(Activity activity) {
     }
 
     public String getDefaultStorageLocation() {
-        return Environment.getExternalStorageDirectory().getAbsolutePath() +
-                pdfDirectory;
+        File dir = new File(Environment.getExternalStorageDirectory().getAbsolutePath(),
+                            PATH_SEPERATOR + pdfDirectory + PATH_SEPERATOR);
```
Comment (McModknower) [inline app/src/main/java/swati4star/createpdf/util/StringUtils.java:72]: The "PATH_SEPERATOR" here is not needed

**Review by Swati4star — APPROVED** [review]
